package app.leesh.tratic.analyze.domain.interpretation;

public enum AnalyzeScenario {
    BULLISH_BREAKOUT_EXTENSION,
    BEARISH_BREAKOUT_EXTENSION,
    BULLISH_TREND_CONTINUATION,
    BEARISH_TREND_CONTINUATION,
    DISTRIBUTION_WARNING,
    ACCUMULATION_WARNING,
    FAILED_BREAKOUT_RISK,
    RANGE_ROTATION,
    LOW_VOL_COMPRESSION,
    INDECISIVE_TRANSITION
}
